# Generated by Django 5.1.7 on 2025-04-08 11:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Primary Key', primary_key=True, serialize=False)),
                ('code', models.TextField(help_text='Code content')),
                ('language', models.CharField(blank=True, help_text='The language in which the code is written. (C/C++)', max_length=20)),
                ('generatedReport', models.CharField(blank=True, help_text='Foreign Key of the Report', max_length=100, null=True)),
                ('submittedBy', models.ForeignKey(help_text='Foreign Key of the User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exploit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Primary Key', primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the exploit and its intended behavior')),
                ('code', models.ForeignKey(help_text='Foreign Key of Code', on_delete=django.db.models.deletion.CASCADE, related_name='exploits', to='api.code')),
            ],
        ),
        migrations.CreateModel(
            name='Patch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Primary Key', primary_key=True, serialize=False)),
                ('patchedCode', models.TextField(help_text='The secure version of the code after applying the patch')),
                ('description', models.TextField(blank=True, help_text='Detailed explanation of the patch and how it mitigates the vulnerability')),
                ('code', models.ForeignKey(help_text='Foreign Key of Code', on_delete=django.db.models.deletion.CASCADE, related_name='patches', to='api.code')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Primary Key', primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='The content of the report')),
                ('format', models.CharField(choices=[('PDF', 'PDF'), ('HTML', 'HTML'), ('Markdown', 'Markdown'), ('Text', 'Text')], help_text='The format in which the report is generated (e.g., PDF, HTML, Markdown, Text)', max_length=20)),
                ('code', models.ForeignKey(help_text='Foreign Key of Code', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.code')),
            ],
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Primary Key', primary_key=True, serialize=False)),
                ('cweId', models.CharField(help_text='CWE (Common Weakness Enumeration) identifier associated with this vulnerability', max_length=50)),
                ('cvssScore', models.DecimalField(blank=True, decimal_places=1, help_text='CVSS (Common Vulnerability Scoring System) score, ranging from 0.0 to 10.0', max_digits=3, null=True)),
                ('severity', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], help_text='Severity classification of the vulnerability', max_length=6)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the vulnerability')),
                ('code', models.ForeignKey(help_text='Foreign Key of Code', on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='api.code')),
            ],
        ),
    ]
