# Generated by Django 5.1.6 on 2025-05-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_report_format_pentestreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='createdAt',
            field=models.DateField(auto_now=True),
        ),
    ]
