# Generated by Django 5.1.6 on 2025-05-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_code_createdat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='generatedReport',
        ),
        migrations.AddField(
            model_name='code',
            name='name',
            field=models.CharField(default='Default', help_text='Project Name', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='code',
            name='createdAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
